### ISSUE TITLE
Activate Prestige Not Working Properly

### ISSUE THREAD

**Issue by amrurikaj** [h1-mod/h1-mod#274] opened 2022-09-16 14:27 UTC
Steps to reproduce:

1. 1.At main menu, go to stats.
2. Enabled Unlock All Items.
3. Enabled Unlock All Loot.
4. Enabled Unlock All Classes.
5. Set prestige to 0.
6. Set Rank to 55.
7. Play until end of 55 level bar.
8. Go to barracks.
9. Go to prestige.
10. Activate prestige.

Expected Result:
Prestige is Activated and no error show.

Actual Result:
Prestige is Activated but there are an error show. Below is the image provided.

![2022-09-16_20_21_06-Call_of_Duty__Modern_Warfare_Remastered_Multiplayer](https://user-images.githubusercontent.com/113702897/190662614-716f8f9c-25a6-45eb-9ce9-4c4be56fdb64.png)

**Comment by amrurikaj** [comment] 2022-09-16 15:25
Tested with 
Not Enabled Unlock All Items.
Not Enabled Unlock All Loot.
Not Enabled Unlock All Classes.

Also will have same problem.

**Comment by mjkzy** [comment] 2022-09-16 17:00
this is because of our demonware emulation. we do not provide the data to return back to PublicProfileInfo and therefore, when it tries to run `PublicProfileInfo::deserialize`, it crashes parsing the byte data. it's a harmless error, but in reality, it does work.

**Comment by amrurikaj** [comment] 2022-09-17 00:59
> this is because of our demonware emulation. we do not provide the data to return back to PublicProfileInfo and therefore, when it tries to run `PublicProfileInfo::deserialize`, it crashes parsing the byte data. it's a harmless error, but in reality, it does work.

i see.do you think we should close this issue or maybe just leave it open?

**Comment by skkuull** [comment] 2022-09-17 18:24
The game will actually crash if you do so but if you restart your game you'll realize that your prestige actually upgraded , and this is already a duplicate of #180 so i'll leave it opened.

**Comment by mjkzy** [comment] 2022-09-17 18:30
i'm not entirely sure if PublicProfileInfo deserializes any other information so i don't know if it is safe to get rid of the execution of this function. however, we could also just provide valid data which may not be too bad to do

**Comment by mjkzy** [comment] 2022-10-07 19:11
bumping this - does a missing DW task show in the external console before it crashes? if so, can you send that ID and task

**Comment by amrurikaj** [comment] 2022-10-08 07:52
> bumping this - does a missing DW task show in the external console before it crashes? if so, can you send that ID and task

@mjkzy  i dont think so. but i have a video and also i copy the error also from the cmd console.





here they are:
[log.txt](https://github.com/h1-mod/h1-mod/files/9738708/log.txt)

https://user-images.githubusercontent.com/113702897/194696609-67f66916-fda4-43ce-a827-c9b9a0f0750d.mp4

**Comment by mjkzy** [comment] 2022-10-10 21:08
looking into it, it seems to be task 24 of bdStorage, which is related to uploading validating files "commondata" and "mpdata". was able to reproduce with same steps but i used `prestigeReset` command. looking into fix

**Comment by amrurikaj** [comment] 2022-10-10 23:25
> looking into it, it seems to be task 24 of bdStorage, which is related to uploading validating files "commondata" and "mpdata". was able to reproduce with same steps but i used `prestigeReset` command. looking into fix

nice 😎

**Comment by mjkzy** [comment] 2022-12-23 13:10
honestly, gonna close as not important because in reality, it's a harmless error and a simple restart shows it really went thru. it is quite annoying tho

**Closed by mjkzy** 2022-12-23 13:10 UTC
Labels: bug, low priority
